package main

import("encoding/json";"flag";"fmt";"os";"os/exec";"path/filepath";"runtime";"strings";inst "tialloystudio/internal/installer")
const product="Ti Alloy Studio"
func psq(s string)string{return "'"+strings.ReplaceAll(s,"'","''")+"'"}
func ps(script string)error{return exec.Command("powershell.exe","-NoProfile","-STA","-ExecutionPolicy","Bypass","-Command",script).Run()}
func choose(def string)(string,bool,error){parent:=filepath.Dir(def);script:=`Add-Type -AssemblyName System.Windows.Forms;$d=New-Object System.Windows.Forms.FolderBrowserDialog;$d.Description='Choose parent folder for Ti Alloy Studio';$d.SelectedPath=`+psq(parent)+`;if($d.ShowDialog() -eq 'OK'){[Console]::Write($d.SelectedPath)}`;b,err:=exec.Command("powershell.exe","-NoProfile","-STA","-Command",script).Output();if err!=nil{return "",false,err};s:=strings.TrimSpace(string(b));if s==""{return "",false,nil};if strings.EqualFold(filepath.Base(s),"TiAlloyStudio"){return s,true,nil};return filepath.Join(s,"TiAlloyStudio"),true,nil}
func msg(s string){_=ps(`Add-Type -AssemblyName PresentationFramework;[System.Windows.MessageBox]::Show(`+psq(s)+`,`+psq(product)+`)|Out-Null`)}
func copySelf(dir string)error{p,err:=os.Executable();if err!=nil{return err};b,err:=os.ReadFile(p);if err!=nil{return err};return os.WriteFile(filepath.Join(dir,"Uninstall.exe"),b,0644)}
func shortcuts(dir string){exe:=filepath.Join(dir,"TiAlloyStudio.exe");_=ps(`$w=New-Object -ComObject WScript.Shell;$d=$w.SpecialFolders.Item('Desktop');$s=$w.CreateShortcut((Join-Path $d 'Ti Alloy Studio.lnk'));$s.TargetPath=`+psq(exe)+`;$s.WorkingDirectory=`+psq(dir)+`;$s.Save();$p=[Environment]::GetFolderPath('Programs');$s=$w.CreateShortcut((Join-Path $p 'Ti Alloy Studio.lnk'));$s.TargetPath=`+psq(exe)+`;$s.WorkingDirectory=`+psq(dir)+`;$s.Save()`)}
func installEngines(dir string)error{zipPath:=filepath.Join(dir,"engine-bundle.zip");data,err:=os.ReadFile(zipPath);if err!=nil{return err};if err=inst.VerifyOfflineEngineBundle(data);err!=nil{return err};tmp,err:=os.MkdirTemp("","tialloy-bundle-");if err!=nil{return err};defer os.RemoveAll(tmp);if err=ps(`Expand-Archive -LiteralPath `+psq(zipPath)+` -DestinationPath `+psq(tmp)+` -Force`);err!=nil{return err};eng:=filepath.Join(dir,"engines");_=os.RemoveAll(eng);cmd:=exec.Command("powershell.exe","-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-Command",inst.OfflineEngineInstallScript(eng,tmp));out,err:=cmd.CombinedOutput();_=os.WriteFile(filepath.Join(dir,"engine-install.log"),out,0644);return err}
func smoke(dir string)error{p:=filepath.Join(dir,"smoke.json");if err:=exec.Command(filepath.Join(dir,"TiAlloyStudio.exe"),"--smoke-test-file",p).Run();err!=nil{return err};b,err:=os.ReadFile(p);if err!=nil||!inst.SmokePass(b){return fmt.Errorf("native scientific smoke failed")};e:=filepath.Join(dir,"engine-smoke.json");if err=exec.Command(filepath.Join(dir,"TiAlloyStudio.exe"),"--engine-smoke-file",e).Run();err!=nil{return err};var v struct{Status string `json:"status"`};b,err=os.ReadFile(e);if err!=nil{return err};if json.Unmarshal(b,&v)!=nil||v.Status!="PASS"{return fmt.Errorf("mature-engine cross-check failed")};return nil}
func main(){un:=flag.Bool("uninstall",false,"uninstall");noLaunch:=flag.Bool("no-launch",false,"no launch");idir:=flag.String("install-dir","","install directory");flag.Parse();if runtime.GOOS!="windows"{os.Exit(2)};if *un{exe,_:=os.Executable();dir:=filepath.Dir(exe);msg("Ti Alloy Studio will be removed.");tmp:=filepath.Join(os.TempDir(),"TiAlloyStudio-remove.cmd");_=os.WriteFile(tmp,[]byte(fmt.Sprintf("@echo off\r\ntimeout /t 2 /nobreak >nul\r\nrmdir /s /q \"%s\"\r\ndel \"%%~f0\"\r\n",dir)),0644);_=exec.Command("cmd.exe","/C","start","","/min",tmp).Start();return};dir:=strings.TrimSpace(*idir);if dir==""{var ok bool;var err error;dir,ok,err=choose(inst.DefaultInstallDir(os.Getenv("LOCALAPPDATA")));if err!=nil||!ok{return}};payload,err:=inst.PayloadFiles();if err!=nil{msg("Installer payload error: "+err.Error());return};if err=inst.InstallPayloadTo(dir,payload);err==nil{err=copySelf(dir)};if err==nil{err=installEngines(dir)};if err==nil{err=smoke(dir)};if err!=nil{_=os.RemoveAll(dir);msg("Installation failed and was rolled back: "+err.Error());return};shortcuts(dir);msg("Installation completed offline. TiModelCore and all bundled scientific engines passed validation.");if !*noLaunch{_=exec.Command("cmd.exe","/C","start","",filepath.Join(dir,"TiAlloyStudio.exe")).Start()}}
