package model
import("errors";"math";"math/rand";"sort")
type PairKey string
type PairShellQuality struct{ShellIndex int `json:"shell_index"`;Distance float64 `json:"distance_angstrom"`;PairCount int `json:"pair_count"`;Observed map[PairKey]float64 `json:"observed_pair_probabilities"`;Target map[PairKey]float64 `json:"target_pair_probabilities"`;Errors map[PairKey]float64 `json:"pair_errors"`;RMS float64 `json:"rms_pair_error"`;MaxAbs float64 `json:"max_abs_pair_error"`;WarrenCowley map[PairKey]float64 `json:"warren_cowley"`}
type SQSQuality struct{Shells []PairShellQuality `json:"shells"`;Objective float64 `json:"objective"`;MaxAbsPairError float64 `json:"max_abs_pair_error"`}
type SQSResult struct{Structure Structure `json:"structure"`;Quality SQSQuality `json:"quality"`;InitialObjective float64 `json:"initial_objective"`;Convergence []float64 `json:"convergence"`;Seed int64 `json:"seed"`;Steps int `json:"steps"`;Engine string `json:"engine"`}
type pairShell struct{index int;distance float64;pairs [][2]int}
func pairKey(a,b string)PairKey{if a>b{a,b=b,a};return PairKey(a+"-"+b)}
func buildPairShells(s Structure,nShells int,tol float64)([]pairShell,error){if nShells<1{return nil,errors.New("n_shells must be >=1")};type rec struct{d float64;i,j int};var all []rec;frac:=s.Fractional(false);for i:=0;i<len(frac)-1;i++{for j:=i+1;j<len(frac);j++{d:=VSub(frac[j],frac[i]);for a:=0;a<3;a++{if s.PBC[a]{d[a]-=math.Round(d[a])}};dist:=Norm(FracToCart(d,s.Cell));if dist>1e-10{all=append(all,rec{dist,i,j})}}};sort.Slice(all,func(i,j int)bool{return all[i].d<all[j].d});groups:=[][]rec{};for _,r:=range all{if len(groups)==0{groups=append(groups,[]rec{r});continue};g:=groups[len(groups)-1];mean:=0.0;for _,x:=range g{mean+=x.d};mean/=float64(len(g));if math.Abs(r.d-mean)<=tol{groups[len(groups)-1]=append(groups[len(groups)-1],r)}else{groups=append(groups,[]rec{r})};if len(groups)>nShells&&r.d-groups[nShells-1][0].d>tol{break}};if len(groups)<nShells{return nil,errors.New("not enough neighbor shells")};out:=make([]pairShell,nShells);for k:=0;k<nShells;k++{mean:=0.0;for _,r:=range groups[k]{mean+=r.d;out[k].pairs=append(out[k].pairs,[2]int{r.i,r.j})};out[k].index=k+1;out[k].distance=mean/float64(len(groups[k]))};return out,nil}
func sqsQuality(species []string,shells []pairShell)SQSQuality{counts:=map[string]int{};for _,e:=range species{counts[e]++};elems:=make([]string,0,len(counts));for e:=range counts{elems=append(elems,e)};sort.Strings(elems);conc:=map[string]float64{};for e,n:=range counts{conc[e]=float64(n)/float64(len(species))};target:=map[PairKey]float64{};for i,a:=range elems{for _,b:=range elems[i:]{if a==b{target[pairKey(a,b)]=conc[a]*conc[b]}else{target[pairKey(a,b)]=2*conc[a]*conc[b]}}};out:=SQSQuality{};sum2:=0.0;nerr:=0;maxall:=0.0;for _,sh:=range shells{obsCount:=map[PairKey]int{};direct:=map[string]map[string]int{};for _,a:=range elems{direct[a]=map[string]int{}};for _,p:=range sh.pairs{a,b:=species[p[0]],species[p[1]];obsCount[pairKey(a,b)]++;direct[a][b]++;direct[b][a]++};obs:=map[PairKey]float64{};errs:=map[PairKey]float64{};wc:=map[PairKey]float64{};s2:=0.0;mx:=0.0;for k,t:=range target{obs[k]=float64(obsCount[k])/float64(len(sh.pairs));errs[k]=obs[k]-t;s2+=errs[k]*errs[k];mx=math.Max(mx,math.Abs(errs[k]));sum2+=errs[k]*errs[k];nerr++};for _,center:=range elems{tot:=0;for _,n:=range elems{tot+=direct[center][n]};for _,n:=range elems{v:=math.NaN();if tot>0&&conc[n]>0{conditional:=float64(direct[center][n])/float64(tot);v=1-conditional/conc[n]};wc[PairKey(center+"->"+n)]=v}};rms:=math.Sqrt(s2/float64(len(target)));out.Shells=append(out.Shells,PairShellQuality{sh.index,sh.distance,len(sh.pairs),obs,target,errs,rms,mx,wc});maxall=math.Max(maxall,mx)};if nerr>0{out.Objective=math.Sqrt(sum2/float64(nerr))};out.MaxAbsPairError=maxall;return out}
func GenerateSQS(host Structure,alloc CompositionAllocation,seed int64,nShells,steps int,tol float64)(SQSResult,error){shells,err:=buildPairShells(host,nShells,tol);if err!=nil{return SQSResult{},err};initial:=RandomSubstitution(host,alloc,seed);cur:=append([]string(nil),initial.Species...);q:=sqsQuality(cur,shells);initialObj:=q.Objective;best:=append([]string(nil),cur...);bestq:=q;conv:=[]float64{q.Objective};rng:=rand.New(rand.NewSource(seed+7919));t0,t1:=0.02,1e-4;for st:=0;st<steps;st++{i,j:=rng.Intn(len(cur)),rng.Intn(len(cur));if i==j||cur[i]==cur[j]{conv=append(conv,bestq.Objective);continue};cur[i],cur[j]=cur[j],cur[i];cand:=sqsQuality(cur,shells);delta:=cand.Objective-q.Objective;f:=float64(st)/math.Max(1,float64(steps-1));temp:=t0*math.Pow(t1/t0,f);accept:=delta<=0||rng.Float64()<math.Exp(-delta/temp);if accept{q=cand;if cand.Objective<bestq.Objective-1e-15{bestq=cand;best=append([]string(nil),cur...)}}else{cur[i],cur[j]=cur[j],cur[i]};conv=append(conv,bestq.Objective)};out:=host;out.Species=best;out.Meta=cloneMeta(host.Meta);out.Meta["model_kind"]="sqs";out.Meta["sqs_objective"]=bestq.Objective;return SQSResult{out,bestq,initialObj,conv,seed,steps,"TiModelCore pair-statistics annealer"},nil}
